name: Build and Deploy to GitHub Pages

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  # Only run if the PR was merged (not simply closed)
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install Playwright
        run: deno task install:playwright

      - name: Build artifacts
        run: deno task build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: |
            index.svg
            index.gif
            index.html
            README.md

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}

    # Grant permissions for GitHub Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
